name: Restore build cache
description: Installes node, pnpm, and restores the build cache
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Restore build
      uses: actions/cache@v3
      with:
        path: ./*
        key: ${{ github.sha }}-${{ github.run_number }}
